//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimsApp
{
    public partial class Home
    {
        // Modernization: Use nullable reference types for better null safety
        // Add the nullable annotation to all reference types
        
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm? form1;

        /// <summary>
        /// lblWelcome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label? lblWelcome;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button? btnLogout;

        /// <summary>
        /// pageTitle control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl? pageTitle;

        /// <summary>
        /// lblSucessMessage control.
        /// </summary>
        // Modernization: Fix typo in variable name
        protected global::System.Web.UI.WebControls.Label? lblSuccessMessage;

        /// <summary>
        /// btnRegisterComplaint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button? btnRegisterComplaint;

        /// <summary>
        /// gvComplaints control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView? gvComplaints;

        // Modernization: Add a constructor to initialize fields if necessary
        public Home()
        {
            // Initialize fields here if needed
        }

        // Modernization: Add a method to validate that all controls are properly initialized
        protected void ValidateControls()
        {
            if (form1 == null) throw new InvalidOperationException("form1 is not initialized");
            if (lblWelcome == null) throw new InvalidOperationException("lblWelcome is not initialized");
            if (btnLogout == null) throw new InvalidOperationException("btnLogout is not initialized");
            if (pageTitle == null) throw new InvalidOperationException("pageTitle is not initialized");
            if (lblSuccessMessage == null) throw new InvalidOperationException("lblSuccessMessage is not initialized");
            if (btnRegisterComplaint == null) throw new InvalidOperationException("btnRegisterComplaint is not initialized");
            if (gvComplaints == null) throw new InvalidOperationException("gvComplaints is not initialized");
        }
    }
}