//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimsApp
{
    public partial class Login
    {
        // Using 'required' modifier for better null safety
        // Comment: Added 'required' modifier to ensure these fields are initialized
        public required HtmlForm form1 { get; set; }
        public required TextBox txtUsername { get; set; }
        public required TextBox txtPassword { get; set; }
        public required Button btnLoginUser { get; set; }
        public required Label lblMessage { get; set; }

        // Comment: Removed individual XML comments for each control
        // as they were redundant and cluttered the code

        // Comment: Removed 'protected' access modifier as it's not necessary in partial classes
        // Comment: Changed from fields to auto-implemented properties for better encapsulation
        // Comment: Removed 'global::' prefix as it's not necessary in most cases
    }
}