//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimsApp
{
    public partial class Home
    {
        // Modernized: Use of nullable reference types
        // Modernized: Changed to public properties instead of protected fields for better encapsulation
        // Modernized: Use of 'required' keyword for non-nullable properties

        /// <summary>
        /// form1 control.
        /// </summary>
        public required HtmlForm Form1 { get; set; }

        /// <summary>
        /// lblWelcome control.
        /// </summary>
        public required Label LblWelcome { get; set; }

        /// <summary>
        /// btnLogout control.
        /// </summary>
        public required Button BtnLogout { get; set; }

        /// <summary>
        /// pageTitle control.
        /// </summary>
        public required HtmlGenericControl PageTitle { get; set; }

        /// <summary>
        /// lblSucessMessage control.
        /// </summary>
        // Modernized: Fixed typo in property name
        public required Label LblSuccessMessage { get; set; }

        /// <summary>
        /// btnRegisterComplaint control.
        /// </summary>
        public required Button BtnRegisterComplaint { get; set; }

        /// <summary>
        /// gvComplaints control.
        /// </summary>
        public required GridView GvComplaints { get; set; }
    }
}