//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimsApp
{
    public partial class Home
    {
        // Modernized: Use nullable reference types for better null safety
        // Comment: Enable nullable reference types in project settings
        
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm? form1;

        /// <summary>
        /// lblWelcome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label? lblWelcome;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button? btnLogout;

        /// <summary>
        /// pageTitle control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl? pageTitle;

        /// <summary>
        /// lblSucessMessage control.
        /// </summary>
        // Modernized: Fixed typo in variable name
        // Comment: Renamed lblSucessMessage to lblSuccessMessage for correctness
        protected global::System.Web.UI.WebControls.Label? lblSuccessMessage;

        /// <summary>
        /// btnRegisterComplaint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button? btnRegisterComplaint;

        /// <summary>
        /// gvComplaints control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView? gvComplaints;

        // Modernized: Added a method to initialize controls
        // Comment: This helps ensure all controls are properly initialized
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            InitializeControls();
        }

        // Modernized: Added a method to initialize controls
        // Comment: This helps ensure all controls are properly initialized
        private void InitializeControls()
        {
            form1 ??= new System.Web.UI.HtmlControls.HtmlForm();
            lblWelcome ??= new System.Web.UI.WebControls.Label();
            btnLogout ??= new System.Web.UI.WebControls.Button();
            pageTitle ??= new System.Web.UI.HtmlControls.HtmlGenericControl();
            lblSuccessMessage ??= new System.Web.UI.WebControls.Label();
            btnRegisterComplaint ??= new System.Web.UI.WebControls.Button();
            gvComplaints ??= new System.Web.UI.WebControls.GridView();
        }
    }
}