//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimsApp
{
    public partial class Home
    {
        // Modernized: Use of 'public' instead of 'protected' for better encapsulation
        // Modernized: Use of 'required' keyword to ensure non-null values
        // Modernized: Use of 'HtmlForm' from Microsoft.AspNetCore.Components.Forms namespace
        public required Microsoft.AspNetCore.Components.Forms.HtmlForm Form { get; set; }

        // Modernized: Use of 'Label' from Microsoft.AspNetCore.Components.Forms namespace
        public required Microsoft.AspNetCore.Components.Forms.Label WelcomeLabel { get; set; }

        // Modernized: Use of 'Button' from Microsoft.AspNetCore.Components.Forms namespace
        public required Microsoft.AspNetCore.Components.Forms.Button LogoutButton { get; set; }

        // Modernized: Use of 'ElementReference' for referencing HTML elements
        public required Microsoft.AspNetCore.Components.ElementReference PageTitle { get; set; }

        // Modernized: Use of 'Label' from Microsoft.AspNetCore.Components.Forms namespace
        public required Microsoft.AspNetCore.Components.Forms.Label SuccessMessageLabel { get; set; }

        // Modernized: Use of 'Button' from Microsoft.AspNetCore.Components.Forms namespace
        public required Microsoft.AspNetCore.Components.Forms.Button RegisterComplaintButton { get; set; }

        // Modernized: Use of 'DataGrid' from Microsoft.AspNetCore.Components.Web namespace
        public required Microsoft.AspNetCore.Components.Web.DataGrid<Complaint> ComplaintsGrid { get; set; }

        // Modernized: Added a class to represent the Complaint data
        public class Complaint
        {
            public int Id { get; set; }
            public string Description { get; set; }
            public DateTime Date { get; set; }
            public string Status { get; set; }
        }
    }
}